# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e63a60cd6b66532ab818945040f3c4c4263ffb67d949c75a068e5f89edbc5f3f542ebea1a892bd2553f9883657d4e7031af2f488247ef2afe2d33ce3444366d2
  secret_key_forcast_io: <%= ENV["SECRET_KEY_FORCAST_IO"] %>

test:
  secret_key_base: d88d789abda9d767a2d42c4010ad5ccaba6139e655168581aee5d2d4da14b0bffecf59b44e4053f448c1d26722e5a742f0d6ef2f356dbbab131ab58a20d89308
  secret_key_forecast_io: <%= ENV["SECRET_KEY_FORECAST_IO"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_forcast_io: <%= ENV["SECRET_KEY_FORCAST_IO"] %>